Fix

diff --git a/.github/workflows/githubaction-comment-plan.yml b/.github/workflows/githubaction-comment-plan.yml
--- a/.github/workflows/githubaction-comment-plan.yml
+++ b/.github/workflows/githubaction-comment-plan.yml
@@ -69,11 +69,12 @@ jobs:
 
     - name: Start LocalStack
       run: |
-        docker run -d \
+        docker run -d --name localstack_container \
         -p 127.0.0.1:4566:4566 \
         -p 127.0.0.1:4510-4559:4510-4559 \
         -v /var/run/docker.sock:/var/run/docker.sock \
         localstack/localstack
+    
     - name: Wait for LocalStack to be ready
       run: |
         echo "Waiting for LocalStack to be ready..."
@@ -85,13 +86,12 @@ jobs:
           echo "Still waiting for LocalStack..."
           echo "Here's Docker info in the meantime:"
           docker ps
-          echo "Here's the CURL:"
-          curl -s http://localhost:4566/_localstack/health
+          echo "Here's the CURL response:"
+          curl -s http://localhost:4566/_localstack/health || echo "Curl command failed with exit code $?"
           sleep 5
         done
         echo "LocalStack did not become ready in time."
         exit 1
-      shell: bash
 
     # Terraform Validation Steps
     - name: terraform validate ${{ inputs.stack }}
